package com.clickkart.repository;

import com.clickkart.entity.Order;
import com.clickkart.entity.OrderItem;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;

/**
 * Repository for the {@link OrderItem} entity (table: order_items).
 *
 * OrderItem rows are INSERT-only after checkout — they are never updated.
 * price_at_purchase is an immutable snapshot; no @Modifying methods are
 * provided here intentionally.
 *
 * ON DELETE RESTRICT on product_id prevents hard-deleting a product that
 * appears on real orders — no delete method on product_id is exposed.
 *
 * Primary consumers:
 *   - OrderService      → build receipt, verify line items
 *   - AdminOrderService → detailed order view, sales analytics
 */
@Repository
public interface OrderItemRepository extends JpaRepository<OrderItem, Long> {

    // =========================================================================
    // Load items for a specific order
    // =========================================================================

    /**
     * Load all line items for a given order.
     * JPQL path: orderItem.order.id
     *
     * Used when the Order entity is already loaded but items were not
     * fetched via JOIN FETCH (e.g., in a lightweight order list view).
     */
    List<OrderItem> findByOrderId(Long orderId);

    /**
     * Load all line items for a given order with product details pre-fetched.
     * Avoids N+1 queries when rendering the receipt / order detail page.
     * Each item's product name, image_url, and price_at_purchase are needed.
     */
    @Query("SELECT oi FROM OrderItem oi JOIN FETCH oi.product WHERE oi.order.id = :orderId")
    List<OrderItem> findByOrderIdWithProduct(@Param("orderId") Long orderId);

    // =========================================================================
    // Product-centric queries (Admin analytics)
    // =========================================================================

    /**
     * All order items that reference a given product.
     * Used by AdminProductService to check before attempting a hard delete —
     * if any items are found, the product must not be deleted (use is_active = false).
     *
     * Also used for sales analytics: "how many units of product X were sold?".
     */
    List<OrderItem> findByProductId(Long productId);

    /**
     * Check whether a product has ever been purchased.
     * Faster than findByProductId() when only existence matters.
     * Used to decide whether hard-delete or soft-delete should be applied.
     */
    boolean existsByProductId(Long productId);

    // =========================================================================
    // Analytics queries (Admin dashboard)
    // =========================================================================

    /**
     * Total units sold for a specific product across all delivered orders.
     * Used for the "Best Sellers" ranking and product analytics.
     *
     * Returns 0 if the product has never been purchased.
     *
     * The status enum value is passed as a bound @Param — Hibernate 6 JPQL
     * cannot resolve inline class path literals (com.x.Enum.VALUE).
     */
    @Query("""
            SELECT COALESCE(SUM(oi.quantity), 0)
            FROM OrderItem oi
            WHERE oi.product.id = :productId
            AND oi.order.status = :status
            """)
    long sumQuantitySoldByProductId(
            @Param("productId") Long productId,
            @Param("status")    Order.OrderStatus status);

    /**
     * Total revenue generated by a specific product (across all delivered orders).
     * Uses price_at_purchase — NOT the current product price.
     *
     * Returns 0.00 if the product has never generated revenue.
     *
     * The status enum value is passed as a bound @Param — Hibernate 6 JPQL
     * cannot resolve inline class path literals (com.x.Enum.VALUE).
     */
    @Query("""
            SELECT COALESCE(SUM(oi.priceAtPurchase * oi.quantity), 0)
            FROM OrderItem oi
            WHERE oi.product.id = :productId
            AND oi.order.status = :status
            """)
    BigDecimal sumRevenueByProductId(
            @Param("productId") Long productId,
            @Param("status")    Order.OrderStatus status);

    /**
     * Top N best-selling products by total units sold (delivered orders only).
     * Returns Object[] rows: [productId, productName, totalUnitsSold]
     * Used to populate the admin "Top Products" dashboard widget.
     *
     * The status enum value is passed as a bound @Param — Hibernate 6 JPQL
     * cannot resolve inline class path literals (com.x.Enum.VALUE).
     */
    @Query("""
            SELECT oi.product.id, oi.product.name, SUM(oi.quantity) AS totalSold
            FROM OrderItem oi
            WHERE oi.order.status = :status
            GROUP BY oi.product.id, oi.product.name
            ORDER BY totalSold DESC
            """)
    List<Object[]> findTopSellingProducts(
            @Param("status")   Order.OrderStatus status,
            org.springframework.data.domain.Pageable pageable);
}
